### ISSUE TITLE
"Default text" property not working in Table

### ISSUE THREAD

**Issue by clementarchi** [archi-contribs/form-plugin#12]
Hello Hervé,

I can't force a "default text" when I'm configuring a textbox in a table (it works fine when I'm not doing it in a table). Whether I do it with the graphical editor or directly in the conf file, it always disappear.
I am using the 1.8.3 version.

Thanks for your help.

**Comment by herve91** [comment]
Working on it. New version should be released in 1 or 2 weeks time.

Best regards
Hervé

**Comment by herve91** [comment]
Done, will be part of next release.

Best regards
Hervé
