### ISSUE TITLE
Form sizing issues on Linux with Display Scaling for 4K monitor

### ISSUE THREAD

**Issue by steve-d-mottram** [archi-contribs/form-plugin#14]
Hi, I am using your form plugin v1.8.5 on Archi 4.2, on Fedora Linux with a 4k monitor. To make the display usable, Archi.ini has the property -Dswt.autoScale=200 set, which makes SWT scale the Archi UI icons and text comfortably. All of the Archi UI handles this fine, except for the Forms and Databases plugins. 

On the Forms Preferences page, the UI initially displays OK, but when I press the "New" button, the preferences form has overlapping and obscured components and is not usable - see the attached screen shot.
![screenshot from 2018-06-20 11-24-48](https://user-images.githubusercontent.com/8301525/41653429-f4d1369a-747d-11e8-94e0-b0e14959211c.png)

I have had similar issues with the Database plugin, though not as severe. Since the other Archi GUI forms and controls work fine, I assume that there is something different about how your plugins display their GUI which is affected by this issue. I'm happy to perform whatever tests you need to help debug this.
Thanks for your great work on both plugins - they are really important in extending Archi's capabilities.

**Comment by herve91** [comment]
Hi,

If I remember correctly, I experience issues as well using the scale factor ... but this was with an older version of Archi. 4.2 should natively deal with hiDPI, at least, it is the case on Windows.

May be the trick I used is still necessary for Linux ... Please have a look in the following post on Archi's forum: [http://forum.archimatetool.com/index.php?topic=240.msg1289#msg1289](url) and let me know.

**Comment by steve-d-mottram** [comment]
Hi - Thanks for the link. This fix is windows-specific for versions before Windows 10, which does a better job of handling scaling. On modern versions of linux, the display system is DPI-aware, but Archi (due to the version of the SWT toolkit used) isn't. Setting the -Dswt.autoScale=200 property in Archi.ini fixes this by telling the SWT toolkit to scale with a specific factor.

The curious thing is that the rest of the Archi UI works fine, so I wondered if there are any specific size calculations in your plugins UI code? I had a quick look, but wasn't able to understand it well enough - in my former coding days I was a middleware developer and kept away from UIs (!)

**Comment by herve91** [comment]
I will create a vitrtual machine with Fedora Linux on my 4K monitor and work on your issue. Are you using KDE,  Gnome or something else ?

At the moment, the "Configuration files" height is calculated automatically by SWT but this calculation may be different on Linux and Windows.

**Comment by steve-d-mottram** [comment]
That's great - thanks for looking at it. I am on Fedora 28 with Gnome desktop - the default that you get when you install Fedora workstation. It's on a 4K 28 inch monitor with the Gnome desktop scaling set to 200% in the Settings app. Let me know if you want me to try anything on my system.

**Comment by herve91** [comment]
Hi Steve,

Just to let you know that I installed a Fedora virtual machine and I succeeded to reproduce your issue. So I should be able to deliver an update that works on Linux.

I'll do my best to deliver it before my holidays this coming Friday ...

**Comment by steve-d-mottram** [comment]
Hi Hervé - that's great, thank you. Hope you enjoy your holiday.

**Comment by herve91** [comment]
Hi Steve,

I installed Fedora 28 on a standard display (1080p) and reproduced your issue as well.

This means that your issue is not related to the 4K monitor nor the -Dswt.autoScale=200 parameter. So I believe that I need to completely rewrite the graphical objects placement and this will take some time.

It will be one of my priorities when I come back from vacation ...

Best regards
Hervé

**Comment by steve-d-mottram** [comment]
Hi Hervé - thanks very much for investigating. Unfortunate that it needs more work than expected, but I guess this will make the tool more robust in the long term. I'm happy to help with any testing or extra information. Have a good vacation.

**Comment by herve91** [comment]
Hi Steve,

My apologies for not having answered to you earlier.

Just to let you know that I'm actively working on your issue on a Fedora virtual machine with a 4K display. I experienced a lot of issues to have a Eclipe and Archi working but eventually found that I needed to increase the maximum number of open files (ulimit).

My key issue is that the rendering is different from a standard size display to a 4K display, and different as well from Windows to Linux. So I'm spending quite some time to change some display parameters on Linux and check their impact on Windows.

This said, I should be able to come back to you with new versions of my plugins in the coming days.

Best regards
Hervé

**Comment by steve-d-mottram** [comment]
Hi - that's great news, thanks for updating me. I'll be able to do any testing you need on Windows and Fedora, at 4K and HD resolutions. It's disappointing that the SWT toolkit is not as platform-independent as we might wish.Kind regards,
Steve

**Comment by herve91** [comment]
Yes, I also discovered that having multi lines labels is not done the same way, SWT_MULTI in one case, SWT.WRAP in the other. So I need to check the OS each time I create a multi line label ...

**Comment by herve91** [comment]
Hi Steve,

I just publish the version 1.8.8 in a test folder. I've got strange behaviour on my VM so I prefer you check on your Linux machine before I release the fix to everyone.

By the way, I applied the same changes on my database plugin (version 2.1 beta 9.6.1 in the test sub-folder as well). If you wish to have a look. You can create a sqlite database which is just a file on any file system if you do not have an existing database.

Best regards
Hervé

**Comment by steve-d-mottram** [comment]
Hi Hervé,

Thanks for the preview! I'm testing now. So far it is looking much better - the preferences window displays correctly and the buttons work as expected. There are some very minor cosmetic issues (e.g. extra padding underneath the online help area, see attached screenshot), but probably not worth the effort of fixing.
![dialog](https://user-images.githubusercontent.com/8301525/44851657-f6a66680-ac58-11e8-8c69-244ac4bef82f.png)

There is one issue with the graphical form editor - the filter control has icons that are squashed horizontally - see the second screenshot here, issue circled in red.
![editor](https://user-images.githubusercontent.com/8301525/44862371-768cfa80-ac72-11e8-9953-95e9ae490a4a.png)

I'll keep testing and let you know if I see anything else. Thanks very much for working on this.

Steve

**Comment by herve91** [comment]
Thank you

The sooner people raise issues, the sooner they're solved :-)
