### ISSUE TITLE
Regexp not working in table columns

### ISSUE THREAD

**Issue by steve-d-mottram** [archi-contribs/form-plugin#16]
Hi - I have created a form with a table, and this works well. However, when I set a regexp on a table column this doesn't seem to do anything - there is no red/green highlighting of values that match or fail to match the regexp. I'm guessing that implementing this feature in tables is not done yet?

**Comment by herve91** [comment]
Hi Steve

It should definitively works. I'll double check when I come back from vacation in few weeks :-)

Best regards
Hervé

**Comment by herve91** [comment]
My apologies for this very long delay.

This will be solved in the next release 1.8.10
