### ISSUE TITLE
[Feature] Give tables a ${rownum} variable

### ISSUE THREAD

**Issue by steve-d-mottram** [archi-contribs/form-plugin#17]
Hi - I am using a table to create properties on an Archimate Data Object that represent the fields of that object. Each table row represents a field of the object. I have the form updating properties named Field[1].name, Field[1].type, Field[1].Length .... Field[n].name, Field[n].type, Field[n].Length and so-on. The problem with this approach is that I have to pick an arbitrary number [n] of fields which will be the maximum for the Data Object, and create Properties for every one of them in the form configuration.

What I would really like to do is define the property names as "Field[${rownum}].Name" and so-on, so that the properties get created as the table grows, and I don't have to pre-define a fixed set of properties. I realise this would require a user interface control to dynamically add or remove rows from the table, and the table would have to maintain its sort order between times when the form plugin is opened.

Just an idea - not sure how feasible this is.

**Comment by herve91** [comment]
Hi Steve

I believe it should no r be too difficult to implement ... but as I'm currently on vacation :-)  I'll study your request when I come back in few weeks :-)

Best regards
Hervé

**Comment by herve91** [comment]
Sorry but I haven't found a simple way to do it. The order of the components in the tables depends on Archi sor I cannot garantee to maintain the order between the form calls.
