### ISSUE TITLE
Setting variable name in a label or text field

### ISSUE THREAD

**Issue by bourboule** [archi-contribs/form-plugin#19]
Hi Hervé,
is there a way to set a variable name in a littera way?
I would like to set the label property through the form plugin. It means that label text must contain the variable name and not the variable value.
The result should be: label = ${documentation} for example.
But I'm unable to use some escape characters to avoid the replacement of variable name by it's value.
I tried using single quote, backslash,...
Thanks for your help.

**Comment by herve91** [comment]
Hi,

Not sure to understand ... Variables are replaced in labels and default values (fields "text" and "default") but not in "variable" fields, So you can set the label property to be '${documentation}".

As a proove of concept, you may use the following form:
```
{
   "version": 3,
   "org.archicontribs.form": {
      "name": "test",
      "refers": "selected",
      "width": 475,
      height": 120,
      "tabs": [
         {
            "name": "test",
            "controls": [
               {
                  "name": "label",
                  "class": "label",
                  "text": "Please try to set a variable as value:",
                  "x": 10,
                  "y": 10,
                  "height": 15
               },
               {
                  "name": "text",
                  "class": "text",
                  "variable": "${property:label}",
                  "x": 200,
                  "y": 8,
                  "width": 250,
                  "height": 19
               }
            ]
         }
      ]
   }
}
```

![image](https://user-images.githubusercontent.com/9281982/48470956-1e867e80-e7f3-11e8-9795-0bc57aabb2b9.png)

![image](https://user-images.githubusercontent.com/9281982/48470991-30682180-e7f3-11e8-9ad6-4c44ac19da58.png)

Is it what you wish to achieve or did I misunderstood ?

Best regards
Hervé

**Comment by bourboule** [comment]
Hi Hervé, you well understood, thanks.
It's the goal. I just would like to write the formula it in a label object (and not a text field) with default value as a formula.
It's a kind of hidden variable.

**Comment by herve91** [comment]
Hi,

Did you try the sample I wrote. If this dolve your request, shall I close this thread ?

Best regards
Hervé

**Comment by bourboule** [comment]
Hi,
for sure, I tried it and it's working fine.
You can close the thread.
Thanks a lot for your help.

**Comment by herve91** [comment]
you're welcome.
