### ISSUE TITLE
View Relationships Connected to an Element

### ISSUE THREAD

**Issue by audreykoz** [archi-contribs/form-plugin#23]
Hey Herve, 
Love the idea that you suggested on the forum, if you could develop it, that would be great:)

**Comment by herve91** [comment]
My apologies Audrey, as your request here was not precise, I must humbly admit that I had forgotten it ...

For reference, the request is: create a variable ${selected:xxx} that refers to the Archi concept that has been selected for the form.

this will allow filters like:
```json
"filter": {
   "tests": [
      { "attribute": "${class}", "operation": "matches", "value": ".*Relationship"  },
      { "attribute": "${source:id}", "operation": "equals", "value": "${selected:id}" },
      { "attribute": "${target:id}", "operation": "equals", "value": "${selected:id}" }
   ],
   "genre": "AND"
}
```

I'll implement it ASAP but I suggest this small update in case several objects are selected before the form is launched:

- Everywhere a single value is expected, ${selected:xxx} will refer to the first selected object, like in the filter:
```
"operation": "**equals**", "value": "${selected:id}"
``` 
- Everywhere multiple values are expected, ${selected:xxx} will refer to all the selected objects, like in the filter:
```
"operation": "**in**", "value": "${selected:id}"
```

**Comment by audreykoz** [comment]
Gotcha, thank you!

**Comment by gmiard** [comment]
Hi both
I also need this functionality, i.e. accessing the relations of a selected object

**Comment by GeraldGrootRoessink** [comment]
Hi,
This is precisely the funcionality that I am looking for, finding the relations of a selected object and the objects at the other end of the relationship. 
Is this still on the table (after 3 years)?

**Comment by herve91** [comment]
Hi,
to be honest, I haven't work on this plugin for ages now. If you're trying to find all the objects that have got a relationship with your selected object, may be the visualiser included in Archi may be of some use for you ?

**Comment by GeraldGrootRoessink** [comment]
I like to find the behavioral elements that access a  certain business object. Indeed the visualiser  gets me there. Thanks.
