### ISSUE TITLE
Edits to config file causes only a model wide form to be applied

### ISSUE THREAD

**Issue by audreykoz** [archi-contribs/form-plugin#24]
For some reason, edits I've made to my config file have caused my form to run model wide when I run it on a subfolder or view. I can't figure out why this would be happening, as I don't believe that I've made any changes to the file that should have caused this.  
The plugin does work properly with the example config file in the repo, just not with my edited one. Any ideas?
![Screen Shot 2019-05-14 at 10 52 25 AM](https://user-images.githubusercontent.com/22486586/57712572-6bc69a00-7636-11e9-9fea-bb8f5064bedb.png)

**Comment by herve91** [comment]
Hi Audrey,

When you run the graphical editor, there is a field called "refers to" that allows to specify on which component the form applies to. It can be set to:
- selected: the object that is selected in the model
- view; the view in which the object stands (if it is a graphical object of course)
- folder: the folder where the Archimate concept stands
- model: the model
![image](https://user-images.githubusercontent.com/9281982/57726781-26cf5180-7690-11e9-83f8-3855bc9dcc13.png)

Does it solves your issue ?

Best regards
Hervé

**Comment by audreykoz** [comment]
Yes! Thank you so much.
