### ISSUE TITLE
Apply form to multiple items inside a folder

### ISSUE THREAD

**Issue by audreykoz** [archi-contribs/form-plugin#25]
Hey Herve, 
At the current moment, trying to run a form on multiple selected elements inside a folder presents duplicate forms for each element. Is it possible to just run 1 form on several selected objects? 
![Screen Shot 2019-05-16 at 1 48 34 PM](https://user-images.githubusercontent.com/22486586/57879265-a02a8980-77e1-11e9-8853-0777f022b067.png)
Thanks!

**Comment by audreykoz** [comment]
Also apologies for all the issues lately, we're starting to integrate the form plugin into our Archi processes at work and I'm the go-to for this right now.

**Comment by herve91** [comment]
The difficulty is that all the variable mechanism is developed around the assumption that only one object is selected.

So ${name} will be replaced by the name of the selected object.

That's the reason why when you've got several objects selected in your model, the right click menu show you an entry for a form for each object.

Today, I do not see how I can fulfill your request. I keep your request opened in case I found an idea, but I'm not really optimistic as it would mean rewrite the entire code :(

**Comment by audreykoz** [comment]
Ah okay, that makes sense. We can always make a throw-away folder and move objects in/out of it if need be, but thank you.

**Comment by herve91** [comment]
and what if ...

You configure your form to point to the model (or view or folder or whatever) and then, in the table, I add an option the filter.

Today you can filter on class, name, property, ... and what if I add an option to filter on the "is selected in the model" status ?

Would that suit your need ?

**Comment by audreykoz** [comment]
Sure! That would definitely help.

**Comment by herve91** [comment]
Ok, cannot commit to any date, but I'll have a look into it :)

**Comment by herve91** [comment]
In fact, it was a bit easier that I first thought.

Please have a try on the version 1.9 (on MAC, please remember to rename the JAR file, to remove the "v" in front of the version number).

In this new version, the filter has got a new operation called "is selected". Here is a sample configuration file to illustrate this new  filter operation:
```xml
{
   "version": 4,
   "org.archicontribs.form": {
      "name": "test_is_selected",
      "refers": "model",
      "tabs": [
         {
            "name": "new tab",
            "controls": [
               {
                  "class": "table",
                  "name": "list of selected Archimate concepts",
                  "x": 0,
                  "y": 0,
                  "width": 600,
                  "height": 400,
                  "columns": [
                     {
                        "class": "label"
                        "name": "name",
                        "width": 50
                     }
                  ],
                  "lines": [
                     {
                        "name": "all selected",
                        "generate": true,
                        "cells": [
                           "${name}"
                        ],
                        "filter": {
                           "tests": [
                              {
                                 "operation": "is selected"
                              }
                           ]
                        }
                     }
                  ]
               }
            ]
         }
      ]
   }
}
```

Best regards
Hervé

**Comment by audreykoz** [comment]
Awesome, I'll try it out, thank you

**Comment by herve91** [comment]
Hi Audrey,

Does it work as expected ?

Best regards
Hervé

**Comment by herve91** [comment]
no answer
