### ISSUE TITLE
Forms Plugin Not Writing Properties consistently

### ISSUE THREAD

**Issue by reed155** [archi-contribs/form-plugin#28]
Hello, 

I've installed and configured forms to allow for a true/false checkbox for 5 properties.  The properties are: 
Experimental
Current
Near Term
Future
Ideal 
 in that order from left to right in a table.  After first setting up the config file, all the properties are written to the selected element(s) with the correct value (either true or false).  However, after a couple of minutes using the form, only the Experimental, Current, and Ideal are written to the properties, while Near Term and Future are not written as properties, regardless if I have the box checked in the form or not.  

I can fix this issue for a few minutes by building a new config file, however,
 it eventually reverts back tot he same behavior.  

[Doc1.docx](https://github.com/archi-contribs/form-plugin/files/3633077/Doc1.docx)
[NewForm-Config.txt](https://github.com/archi-contribs/form-plugin/files/3633078/NewForm-Config.txt)

**Comment by herve91** [comment]
Hi

Could you please confirm the version of Archi and of the plugin you're using ?

Thanks

**Comment by reed155** [comment]
Achi version 4.5.1 
Plugin version 1.9

**Comment by herve91** [comment]
I will conduct some tests and let you know.

**Comment by reed155** [comment]
Hello herve91, 

Any update on this issue?

**Comment by herve91** [comment]
I haven't had time yet, I'm sorry ...

**Comment by reed155** [comment]
Hello herve91,  Any update on this bug?

**Comment by herve91** [comment]
Hi, my priority was the database plugin ... and I released a new version 2 days ago.

So now, your issue is on the top of the list :)

**Comment by herve91** [comment]
I spent more than on hour and failed to reproduce your issue.

Could you please switch the logger to trace mode and send me the log file after your issue has been reproduced ?

**Comment by reed155** [comment]
[FormPlugin.log](https://github.com/archi-contribs/form-plugin/files/3922076/FormPlugin.log)

Here's a log

**Comment by herve91** [comment]
I've found the error message I was searching for:
           2019-12-04 08:30:20 TRACE   78:FormVariable                   -          --> does not end with "}"

very strange ... the variable does end with a "}"

**Comment by reed155** [comment]
When I was trying to recreate the problem, I used the plugin for the better part of 30 minutes on several different views before I was able to recreate the issue.   I'm not sure if that helps in your search for the problem?

**Comment by herve91** [comment]
it does as now I know where it fails.

The difficulty to investigate is the java code is:

> logger.trace("         getting refered EObject from variable \""+variable+"\" (source object = "+FormPlugin.getDebugName(eObject)+")");
>
> if ( !variable.endsWith("}") ) {
>     logger.trace("         --> \""+variable+"\" does not end with \"}\"");
>     return null;
>}

and you log file is:

> getting refered EObject from variable "${property:Near Term}" (source object = DiagramModelArchimateConnection:"Equipment"(a78499e9-b5c3-456d-ad83-400f146845ca))
> --> does not end with "}"

which means the variable value is "${property:Near Term}" which definitely does ends with a "}"

**Comment by herve91** [comment]
if your issue was quicker to reproduce, it would be easier :-)

**Comment by reed155** [comment]
Near Term is the only variable with a space.  Could this be a contributing factor?

**Comment by herve91** [comment]
no as the variable name is  java String. It can contain spaces, dots, comas, parenthesis, and even newlines. Just my plugin is treating leading "${" and trailing "{".

**Comment by herve91** [comment]
and in your log  file, the error also happens with the Future property (with no space)

**Comment by herve91** [comment]
I've done nearly thousand clicks since we're discussing and the issue still not raises on my desktop.

this one will be hard to track ...

**Comment by herve91** [comment]
by the way, which version of Java are your using (the one included in Archi ?) ?
Are your on Windows, Linux or Mac ?

**Comment by reed155** [comment]
A co-worker has the issue on his PC too (Using MSI version of the Install.  I'm using the portable version of Archi).   

We are both on Windows 10.  Arci 4.5.1 with the latest Collaboration plugin. 

Both using the version of Java that came with Archi.

**Comment by reed155** [comment]
[TestConfig.txt](https://github.com/archi-contribs/form-plugin/files/3923945/TestConfig.txt)

Here's the config file for the form I was executing if that helps.

**Comment by herve91** [comment]
got it ...

your variables have gor carriage return in their names
![image](https://user-images.githubusercontent.com/9281982/70182596-6ae57a80-16e4-11ea-95a9-9a6168eb3134.png)

did you use the graphical editor to create the config file ?

**Comment by herve91** [comment]
if yes, I may have a bug in the graphical generator

**Comment by reed155** [comment]
Yes.  I did use the graphical editor to create the file.

**Comment by herve91** [comment]
so what I can suggest is that you edit your configuration with notepad or any other text editor to remove all the "\r".

This will fix your issue.

Meanwhile, I will add a update the graphical editor to remove trailing carriage returns and release a new plugin version.

**Comment by reed155** [comment]
Thanks.  I'll give that a try tomorrow and let you know how it goes.

**Comment by reed155** [comment]
Hi Herve, 

It looks like the edits to the config file solved my problem.  I'll have some colleagues also load up the file and validate. 

One other thing to mention, if you're changing the GUI:  When you make any edits to the config file, in the lines section, the filter defaults to AND, causing me to make make sure I select OR again before saving. 

![image](https://user-images.githubusercontent.com/55559666/70239951-4b793c80-173a-11ea-949c-bb96e5a23154.png)

**Comment by herve91** [comment]
yes, this one has also been identified :)
