### ISSUE TITLE
Wiki Installation Page Missing Pictures

### ISSUE THREAD

**Issue by whemix** [archi-contribs/form-plugin#29]
Seems like the reference photos from Wiki are missing now.

Screenshot of the 2 sections specifically missing images:

![image](https://user-images.githubusercontent.com/35859671/155866368-17c33b5d-84df-4e76-8b18-417ba151b62c.png)

![image](https://user-images.githubusercontent.com/35859671/155866423-310523c2-54c2-479b-ab2d-5cf16b0755ef.png)

**Comment by herve91** [comment]
You're right ...

Screenshots were taken by @audreykoz and they are not available in her latest branch.

I copied them in a local "screenshots" folder and updated the links.
