### ISSUE TITLE
I can't get "check" to work

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/form-plugin#3]
Hi,

I'm trying to configure a form in which I only show a table that lists all flow relationships together with some properties. On of these properties should be a checkbox but I can't get it to work.

Here is my configuration file:
````
{
	"version": 2,
	"org.archicontribs.form": [
		{
			"name": "Edit flows for view \"${name}\"",
			"refers": "view",
			"width": 1300,
			"height": 400,
			"spacing": 2,
			"buttonOk": "Save changes",
			"buttonCancel": "Cancel",
			"buttonExport": "Export to Excel",
			"buttonWidth": 120,
			"variableSeparator": ">",
			"whenEmpty": "ignore",
			"tabs": [
				{
					"name": "Flows",
					"controls": [
						{
							"class": "table",
							"x": 10,
							"y": 10,
							"width": 1270,
							"height": 300,
							"foreground": "0, 0, 0",
							"excelSheet": "relationships",
							"excelFirstLine": 1,
							"columns": [
								{
									"name": "Source",
									"width": 200,
									"class": "label",
									"excelColumn": "A",
									"excelCellType": "string",
									"excelDefault": "zero"
								},
								{
									"name": "Target",
									"width": 200,
									"class": "label",
									"excelColumn": "B",
									"excelCellType": "string",
									"excelDefault": "zero"
								},
								{
									"name": "Name",
									"width": 200,
									"class": "text",
									"excelColumn": "C",
									"excelCellType": "string",
									"excelDefault": "zero"
								},
								{
									"name": "Documentation",
									"width": 400,
									"class": "text",
									"excelColumn": "D",
									"excelCellType": "string",
									"excelDefault": "zero"
								},
								{
									"name": "Technology",
									"width": 200,
									"class": "combo",
									"values": ["Unknown", "To Be Defined", "CFT", "WebService", "Manual", "Manual (XLS)"],
									"default": "Unknown",
									"excelColumn": "E",
									"excelCellType": "string",
									"excelDefault": "zero"
								},
								{
									"name": "TestCheck",
									"width": 200,
									"class": "check",
									"values": ["Unknown", "To Be Defined"],
									"default": "Unknown",
									"excelColumn": "F",
									"excelCellType": "string",
									"excelDefault": "zero"
								}
							],
							"lines": [
								{
									"generate": true,
									"cells": ["${source>name}", "${target>name}", "${name}", "${documentation}", "${property>Flow:Technology}", "${property>TestCheck"],
									"filter": {
										"tests": [
											{ "attribute": "${class}", "operation": "matches", "value": ".*FlowRelationship" }
										]
									}
								}
							]
						}
					]
				}
			]
		}
	]
}
````

What's wrong with this ? Can you help me please ?

**Comment by herve91** [comment]
Hi JB,

I commented #4 . Do you still need help on this one (I mean for elements and relationships outside groups) ?

Best regards
Hervé

**Comment by jbsarrodie** [comment]
Hi Hervé,

Yes, I need help on this one as it is separated from the other. I still need to be able to us checkbox.

Is my configuration ok "in theory" for a checkbox or do I need to add something else ? Maybe yo ucan provide a simple example that works for you.

Regards

**Comment by herve91** [comment]
I asked the question because I've got no issue with your configuration file and  a view containing two nodes with a flow relationship between them (I just changed the widths to reduce the size of the screenshots).
![2 nodes](https://user-images.githubusercontent.com/9281982/29427480-30a6943e-838a-11e7-8209-a63b4abaa265.png)
![form with 2 nodes](https://user-images.githubusercontent.com/9281982/29427482-35553d50-838a-11e7-826e-999a75a605ac.png)

As the total of the widths of your table column is bigger than the table width, did you notice the scroll bar at the bottom of the table ?

Best regards
Hervé

**Comment by jbsarrodie** [comment]
I can see the same, but nothing is saved when I check the checkbox. This doesn't create nor change the property...

**Comment by jbsarrodie** [comment]
Hi,

FYI I've have received your configuration that I have still to try. I'll let you know soon....

Thank you

**Comment by herve91** [comment]
Hi JB,

Sorry for this late answer. At first, I thought that you did not see the check box, not that the property was not set.

It took me some time to understand what happened ... you are missing the closing brace in the variable name. And obviously, I do not raise any error message in this case :(

Best regards
Hervé

**Comment by jbsarrodie** [comment]
Hi,

Thank you, this now work. What's strange is that I did several test before on another configuration in which there were no such mistake, so maybe I cumulated several issues and different times.

Anyway, this now works fine as expected.

Thank you !

And BTW: great plugin !
