### ISSUE TITLE
.Config Sample File

### ISSUE THREAD

**Issue by whemix** [archi-contribs/form-plugin#30]
Reading the old Archi Forums seems like there used to be a sample .config file included to help users start off with.

![image](https://user-images.githubusercontent.com/35859671/155871439-fe1efdf0-02f6-4483-a0f3-b58177ca5fc1.png)

https://forum.archimatetool.com/index.php?topic=278.0

Was there included one before?  Where can someone get the sample .config file?

**Comment by herve91** [comment]
Hi,

A sample file if provided next to the JAR file: [org.archicontribs.form.conf](https://github.com/archi-contribs/form-plugin/blob/master/org.archicontribs.form.conf)

**Comment by whemix** [comment]
Thank you @herve91 for clarifying.  I did not initially think that was it as I was looking for a file with .config extension.

When I used the sample file I saw this warning message.  It seemed to load fine, except I noticed it changed the .conf file from version 3 to 4.  

What exactly should someone like me take note of?

Thank you and appreciate your patience 🙏

![image](https://user-images.githubusercontent.com/35859671/155913224-b0173312-3d07-4b13-954c-55dfa79c92d4.png)

**Comment by herve91** [comment]
Hi,
Sorry for this very late reply, but as your post has been written after I close the case, I haven't seen it.
Basically, the version 4 of the file allows more components. You may safely use the sample file provided.

Please note that I dod not received any comment or question on this plugin for a very long time so I stopped investing on it. So I even haven't tested it on recent versions of Archi.

**Comment by whemix** [comment]
Thank you for responding despite not having been involved for a long time.  I can say that it still works as of v4.92

**Comment by herve91** [comment]
Thanks for the information.
