### ISSUE TITLE
strange new option(s) on right-click menu

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [archi-contribs/form-plugin#31]
After installing and configuring form-plugin I have a nice new option to see or enter standard parameters for a Archimate-element.  But at the top of the menu, there are one or two more unexpected options.

![afbeelding](https://user-images.githubusercontent.com/20146034/170373661-90518644-0480-45ad-befb-be9d81bfd03c.png)

Maybe the are  harmful?

**Comment by herve91** [comment]
Which options are you talking about ?
The Undo and Redo ones ? If this is the case, they are standard Archi options and are not related to my plugin.

**Comment by GeraldGrootRoessink** [comment]
Thanks,  and they actually undo and redo the last form-transaction.
