### ISSUE TITLE
Form Pluglin

### ISSUE THREAD

**Issue by fsanchez2203** [archi-contribs/form-plugin#32]
Hello Sr. I'm trying to use this pluglin. I did every pass described into the page of instalation, setup  and the archi help. The App Archi shows the plugin as installed, but, it not appear in Preferences menu. I saw that this plugin is compatible with the Arch 4.  Is there any restriction to use it of in Archi 4.10.0?
Best Regards.

Fábio Sanchez.

 
![image](https://user-images.githubusercontent.com/63874112/204809284-e62e5c92-202c-435d-a5d3-61ec34dc7f57.png)
![image](https://user-images.githubusercontent.com/63874112/204809386-5a2d364e-1f0e-4214-a34d-c1c3b753a1bb.png)

**Comment by herve91** [comment]
Dear Fabio,
Even if it's a quite old plugin and if I didn't update the way it works for a long time now, you should definitively see the plugin in your preferences. I even installed it on Achi 5.0 and I can see it in the preferences:
![image](https://user-images.githubusercontent.com/9281982/205446514-64b31dcd-aa2e-40d6-8bb7-51a148e928cd.png)

What I can suggest is to launch Archi with the console log (i.e. run "Archi.exe -consolelog") and check if n error message is raised.

**Comment by fsanchez2203** [comment]
Hello Hervé Jouin.
I run the Archi with the console log. The log registry doesn't show any
message or problem. Is there another procedure that I still can do before
giving up?
I had another doubt. How are you using Archi 5.0 if the last
version available is 4.10.0?

Best regards.

Fábio Sanchez
+351 263 094 286 (Telefone)
+351 910 744 293 (Telemóvel)
e-mail: ***@***.***


Hervé Jouin ***@***.***> escreveu no dia sábado, 3/12/2022
à(s) 14:45:

**Comment by herve91** [comment]
It's because I've got the latest version compiled from the source code available on GitHub, and it's 5.0.

Meanwhile I also installed the plugin on 4.9 and 4.10 of Archi and the entry is present in the preferences pages. Just in case, couls you please uninstall and reinstall it ?

**Comment by Diozavr** [comment]
Also installed (and reinstalled) on 4.10 and context menu not added.
But it appears in Preferences

Updated: It works, only I didn't understood the way it works first time. It's ok when configuration is created

**Comment by herve91** [comment]
To see a form in the context menu, you need to create a form. Did you create one ? As far as I'm concerned, I can see my form in the context menu.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/9281982/207057503-1d1054ab-9564-4adb-a5d2-c7d2773f9e77.png">

Please configure the logger in trace mode and send me the log file that I can investigate what happens on your side.

**Comment by herve91** [comment]
closed as I do not recieved the log file and therefore cannot investigate
