### ISSUE TITLE
Support for specialization

### ISSUE THREAD

**Issue by galsom** [archi-contribs/form-plugin#34]
I tried to access the specialization of a certain element, which was added in Archi 4.9, but am not sure how to do so.

`${name}`, `${class}`, `${specialization}` and `${property:specialization}` do not seem to work.

Is this currently feasible?

**Comment by herve91** [comment]
Spécialisations are not yet managed by the form plugin.

I'll add them and let you know when it's done.

**Comment by herve91** [comment]
Sorry for the very long delai

I added the ${specialization} variable. It is part of the release 1.9.2 that I just sent.

**Comment by galsom** [comment]
Thank you for adding this!

When I tried it out on a specialized element using a table, I get the following error:

`Unknown variable "specialization" (${specialization})`

The element does contain a specialization according to the GUI:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/48659253/231580838-7ee6def5-07d0-4b43-b721-e8c6fea07bbe.png">

And in the Specialization Manager it is also correctly shown:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/48659253/231581021-dce17c33-4c4b-4146-944c-18116ff54c12.png">

Do you know what might cause this?

**Comment by herve91** [comment]
I tested again and it works on my side ...

I created a test form containing a single label with "${name} as ${specialization}" value:
<img width="366" alt="2023-04-13_17h18_28" src="https://user-images.githubusercontent.com/9281982/231806832-ae55d0c1-cc3e-432a-88a8-3382c8c7f453.png">
<img width="416" alt="2023-04-13_17h18_36" src="https://user-images.githubusercontent.com/9281982/231806845-ab0e527d-6e4e-4c48-8896-fb8f6ec5a474.png">

When I run the form, the variable is correctly expanded:
<img width="819" alt="2023-04-13_17h19_03" src="https://user-images.githubusercontent.com/9281982/231806999-bf33253a-15ea-49a5-94e8-865bd299dca0.png">

**Comment by galsom** [comment]
That works for me locally as well when selecting the element, both as a label as you did as well as a label in a table:

<img width="143" alt="image" src="https://user-images.githubusercontent.com/48659253/232468286-73139952-0256-4a14-87a8-b5925736a7f8.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/48659253/232468344-e514ebbe-76e7-44b7-9b0c-3fe860678743.png">

When selecting the view however rather then the element, then the error is thrown:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/48659253/232468560-d05493fe-12fc-412a-be11-f6a31718b74d.png">

I have also tried to filter the table using the new variable, but that has the same effect.

Attached you find both a test model and test form that might help you test if it only happens locally on my side.

[Archive.zip](https://github.com/archi-contribs/form-plugin/files/11249499/Archive.zip)

Let me know if I can be of any help.

**Comment by herve91** [comment]
Views do not have specialization. Only elements and relationships can have one.
