### ISSUE TITLE
support for validating property values against REST Datasources

### ISSUE THREAD

**Issue by schoko123** [archi-contribs/form-plugin#35]
Hi,
It would be very helpful if property values can be validated against and API Restendpoint, to check
if input values match some conditions.
Also values fetched from an REST Endpoint for select list can be very useful.
The configured check on all form values should be triggered on close of the form.
On Error the error should be displayed so that the user can correct the wrong values.

bye schoko

**Comment by herve91** [comment]
Hi Schoko,

I believe it would not be easy to develop a generic check as it needs to adapt to the web service interface contract.

Each time your web service interface changes, you might request a change in the code ...
