### ISSUE TITLE
how to include form-plugin in a packaged version of Archi

### ISSUE THREAD

**Issue by onderwijsarchitectuur** [archi-contribs/form-plugin#37]
Hi,
This wiki contains an instruction to create a distribution package for Archi including plugins to provide my co-workers with an easy setup:

https://github.com/archimatetool/archi/wiki/How-to-create-a-packaged-version-of-Archi-(including-configuration-and-plugins)

I have created some forms for this plugin to describe views and elements in a structured way. I would like them to be in de package as well.   Conforming the wiki I created a default configuration for Archi. Now it contains this entry:

> org.archicontribs.form/configFile_0=M\:\\CIO\\Algemeen\\Tooling\\Archi5\\localdata\\forms\\form_view.config

However I do not control the configuration from every co-worker, so I need a relative path instead of an absolute path. 
 
Is there a way?

Thanks. Gerald

**Comment by herve91** [comment]
Hi Gerald,

The configuration file is opened using the "java.io.File.File" class. Therefore, an absolute path is not mandatory.

Unfortunately, you cannot use environment variables in paths ... This said, the good news is that you can use relative path like "form_view.config" or ".\form_view.config" or "..\folder\form_view.config".

The java.io.File.File documentation indicates that these relative paths refer from the current folder. On my local Archi.exe, running on Windows 10, the current folder is the Documents folder (even if the Archi software is installed in Program Files). Still, I suggest you conduct some tests on your own desktop to validate what is the current folder for your local Archi.exe.

Hope this helps

**Comment by onderwijsarchitectuur** [comment]
Thanks for answering.
I thought I tried that. Must have done something wrong. Tried it again after doing a full Archi reset. This time it works and it finds the forms. Thanks.
Happy with the forms.
Gerald
