### ISSUE TITLE
Elements inside a (visual) Group are not taken into account

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/form-plugin#4]
Hi,

As explained in #3, I'm working on a form that list all relationships on a view.

There seems to be a bug when some elements are inside a (visual) group. In such case elements are not taken into account and some (in my case most) relations are missing in the form.

**Comment by herve91** [comment]
Hi JB,

You're right ... It seems that my plugin ignores the components inside groups. Thanks for pointing out this bug.

Best regards
Hervé

**Comment by herve91** [comment]
solved
