### ISSUE TITLE
Form editor...

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/form-plugin#5]
Hi,

I've seen on the forum that you have started working on a graphical interface to generate the configuration file. I don't know what you've done yet but may I suggest an interresting way of doing it...

...Simply use a Sketch view for that purpose!

Let me explain: I think we could simply use a Sketch view in which we would add "Sticky notes". Each sticky would correspond to a configuration element (a form, a tab, a control, a column...) and its attributes (size, color....) and properties (same name as in current configuration) would be used to generate the configuration. The smart thing with stickies is that they are also containers, so you can use this hierarchy to mimic the logic of your already existing configuration file. This would be very visual and would be very similar to WYSIWYG.

This could look like this:
![form configuration](https://user-images.githubusercontent.com/5757396/29474261-4a40e9fe-845b-11e7-90a1-61bff729c8f2.png)

Some attributes like width and height could be calculated from the size of stickies, but one could also add explicit properties for them (when designing really big forms).

One drawback is that this would be a per model configuration, but this could have some advantage too (when the meaning of form is very related to the model itself and doesn't make sens in other context). In addition, it could be easy to add a way to use this sketch view only as a designer that would serve to generate the JSON file.

What do you think ?

**Comment by herve91** [comment]
Hi JB,

Wow, your idea looks great !!!

If the information is in a sketch view, then it can also be exported a repository (database or Git) and shared across various models. And in this case, I would even not need any configuration file anymore ... just the sketch view.

Still few questions to work out:
- how to retrieve the sticky notes in the right order (which is important for the table columns for instance) ?
- how to provide guidance to the user to fill in the right sticky notes properties ? another form ? so would the plugin generate a standard sketch view to achieve that or would it use an internal configuration ?

On my side, I was more thinking about showing up a tree with the form content with the form aside. Selecting a form component would highlight the component in the form, and changing one of it's property would update the form in real time.

I still need to add the add and remove option and of course the ok and cancel buttons, but I'm nearly done ...
![form editor](https://user-images.githubusercontent.com/9281982/29479415-59237cea-8472-11e7-9fe9-09d5576fdbfb.png)

But it's not too late to change :)

**Comment by jbsarrodie** [comment]
>how to retrieve the sticky notes in the right order (which is important for the table columns for instance) ?

I would just sort them based on their X coordinate

>how to provide guidance to the user to fill in the right sticky notes properties ? another form ? so would the plugin generate a standard sketch view to achieve that or would it use an internal configuration ?

I think a good documentation (like the one in this wiki) and a template model for Archi would be enough. Users would then be able to copy/paste examples coming from this template model.

**Comment by herve91** [comment]
Hi

I close this issue as I prefered to develop a WISIWIG graphical interface.
