### ISSUE TITLE
[Bug] Export To Excel of Forms Plugin of a Table fails

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/form-plugin#7]
Issue from @rich-biker (copied from https://github.com/archimatetool/archi/issues/321)

### Version of Archi, Operating System
archi 4.0.3
org.archicontribs.form plugin 1.8.1 (or earlier)
Windows and Mac

[FormPlugin.log](https://github.com/archimatetool/archi/files/1488296/FormPlugin.log)

### Expected Behaviour
The table should get exported to excel

### Actual Behaviour
I get an error popup of "Failed To update Excel file." "null". 

### Steps to Reproduce the Behaviour
1. By following the form wiki instructions Create a simple form with a table and some lines. I set   "excelFirstLine": 1
2. Run the form and get some data back.
3. Export to excel 

### Workaround
Add this to the config file as well as the excelFirstLine, but set to 1.
                  "excelLastLine": 1,

So either the wiki needs to say this, or the code needs to default last to first.

**Comment by herve91** [comment]
Hi JB,

Thanks for moving this issue here ... I added a default value to the "excelfirstLine" keyword.

It will be solved in the next release.

Best regards
Hervé

**Comment by herve91** [comment]
Hi,

the new release is available and includes a default value for the "excelLastLine" keyword.

Best regards
Hervé
