### ISSUE TITLE
[Issue] Export to Excel not possible on Mac

### ISSUE THREAD

**Issue by rich-biker** [archi-contribs/form-plugin#8]
I use both a Mac and a PC, with the same config files and excel workbook. On my Mac  I am unable to select the .xlsx excel file to export to.  I even excel-saved-as to xls, and this is no different. The excel files remain greyed out.

Archi 4.1.1
Forms Plug-in 1.8.3
Mac OS 10.13.2
Excel 15.34

**Comment by herve91** [comment]
Unfortunately, I haven't got any Mac to do some testing, so it will be quite diffucult for me to understand why it behaves like that.

On PC, the "*.xls*" is just a filter that shows the files that match this filter, and hide the others (but there is not greyed-out files)

What you can try is to select "*" as the filename in thefile explorer, this will bypass the filter and should show up all the files, whatever their extension ...

**Comment by rich-biker** [comment]
The filter only shows *.xls* which doesn't actually find the xls files. There is no option to select just a "*".  See attached, is all I get.

![saveas](https://user-images.githubusercontent.com/18450552/34155296-a8f9caaa-e4b0-11e7-8389-6e14d349a508.png)

p.s. If you want to test any Mac based changes, I'd be happy to try if you send direct.

**Comment by herve91** [comment]
Yes, there is no "*" option, but you should be able to type "*" in the file name text field:
![star filter](https://user-images.githubusercontent.com/9281982/34156656-6f2ac956-e4be-11e7-941b-920ad1e92398.png)

Doing so should show you *all* the files (at least, this works on a PC).

**Comment by rich-biker** [comment]
I've had another look to see if there's a way round it, but no. 

![openexcel](https://user-images.githubusercontent.com/18450552/34174761-fcf262fc-e4f1-11e7-9142-29d75a06d1a9.png)

I've used a Mac for years, unless there's a feature I don't know about, you can't just specify the file name as on a PC as you have shared. I tried using the search field too. The Mac dialog is just different.

**Comment by herve91** [comment]
In this case, I will add a "*" filter in addition to the "*.xls*" one.

I will even try to split it to "*.xls, x*.xlxx, *.xlsm", ... as may be this is the second star that the MAC does not like.

**Comment by rich-biker** [comment]
Thanks - It would also be nice to be able to include an excel template (.xltx) in that (which I'd have preformatted with headers etc) so that exported data doesn't remain in the sheet.

**Comment by herve91** [comment]
yes, I will add all the Excel extensions :)

**Comment by rich-biker** [comment]
I do appreciate your workload - Is this still in your to-do list? I'm still having to use a PC to get exports to excel.

**Comment by herve91** [comment]
Hi,

I will release a new version with this update (and few other ones) in one or two weeks.

Sorry for the delay ...

**Comment by herve91** [comment]
Done, will be part of next release.

The Excel files extension will be "*.xls*", "*.xlt*" and "*.*".

Best regards
Hervé
