### ISSUE TITLE
[Issue] Form column ordering

### ISSUE THREAD

**Issue by rich-biker** [archi-contribs/form-plugin#9]
Clicking on a generated form's column orders ascending or descending (up arrow / down arrow is shown). Great on a PC, however, not the case on a Mac; no ordering behaviour at all. 

Archi 4.1.1
Forms Plug-in 1.8.3
Mac OS 10.13.2

**Comment by herve91** [comment]
Could you please confirm if the up/down arrow show up on Mac or not ?

The library used in Archy relies on graphical objects managed by the operating system. So I wonder if the table header is clickable on Mac or not.

If the arrows are shown on Mac (but the oder not changed), this mean that the table header is selectable and that I need to understand why the sort dioes not work on Mac.

If the arrows are not shown on Mac, this means that the table header is not selectable on Mac and that I won't be able to do much about this issue.

**Comment by rich-biker** [comment]
HI Herve,

I’ve just tried again, and it looks ok now?! (and yes the up/down arrows are fine) Sorry to put you on alert; I’ll close the issue.

Regards,
Richard.
